name: publish

on:
  push:
    branches: [develop]

env:
  NODE_VER: 16.14.0
  DIR: metafox-dev-docs-master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: cache-yarn
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-${{ env.NODE_VER }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VER }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: yarn
      - run: yarn build

      # rebuild frontend documentation
      - name: push to doc repo
        run: |
          rm -rf ${{ env.DIR }
          git clone --single-branch --branch main https://metafoxapp:${{ secrets.API_PERSONAL_TOKEN }}@github.com/metafoxapp/metafox-dev-docs.git ${{ env.DIR }
          cd ${{ env.DIR }
          cp -rf ./../.docz/dist/* ./docs
          git add .
          git commit -m "ci updated"
          git push --force
