name: publish

concurrency: publish_dev_docs

on:
  workflow_dispatch:

env:
  NODE_VER: 16.14.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}

      - uses: actions/cache@v3
        id: cache-yarn
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-${{ env.NODE_VER }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VER }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: |
          yarn
          yarn build
          chmod -R +r out

      - run: |
          echo "Reset Docs"
          date > docs/date.txt
          cp -rf externals/* docs
          cp -rf out/* docs

      - name: Commit files
        run: |
          git config --local user.email "namnv@younetgroup.com"
          git config --local user.name "jacky158"
          git add docs -f
          git commit -m "ci: update docs"
          git push

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
