name: publish

on:
  push:
    branches: [master]

env:
  NODE_VER: 16.14.0

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: cache-yarn
        with:
          path: node_modules
          key: |
            ${{ runner.os }}-${{ env.NODE_VER }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VER }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: yarn
      - run: yarn build

      - uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: .docz/dist/
          remote_user: root
          remote_host: 159.65.143.162
          remote_path: /home/docs/
          remote_key: ${{ secrets.DEPLOY_KEY }}
